In [1]:
l = [2,3,4,5,6]

In [2]:
l.append(9)

In [3]:
l

[2, 3, 4, 5, 6, 9]

In [4]:
def add(a,b):
    return a+b

In [5]:
add(3,4)

7

In [6]:
def hello():
    print('hello')

In [7]:
hello()

hello


In [8]:
l = [3,4,5,6,8,9]
n = len(l)
for i in range(0,n,3):
    print([i])

[0]
[3]


In [9]:
for i in l:
    print(i)

3
4
5
6
8
9


In [10]:
1-----100-----sum

TypeError: bad operand type for unary -: 'builtin_function_or_method'

In [11]:
s = 0
for i in range(1,101):
    s = s+i
    

In [12]:
a = int(input('enter the number :'))
if (a>=1) and (a<=25):
    s = 0
    for i in range(a+1):
        s = s+i
    print(s)
else:
    print('invalid')

enter the number :


ValueError: invalid literal for int() with base 10: ''

In [13]:
* * *
* * *
* * *

SyntaxError: invalid syntax (Temp/ipykernel_11524/3882157624.py, line 1)

In [14]:
print('*')
print('*')

*
*


In [15]:
for i in range(6):
    print('*')

*
*
*
*
*
*


In [16]:
 * * * * * *

SyntaxError: invalid syntax (Temp/ipykernel_11524/3550586482.py, line 1)

In [17]:
for i in range(3):
    print('*',end = ' ')

* * * 

In [18]:
for i in range(3): #----0,1,2
    for j in range(3):
        #----0,1,2
        print(f'{i}{j}',end = ' ')
    print()

00 01 02 
10 11 12 
20 21 22 


In [19]:
# * *
* # *
* * #

SyntaxError: invalid syntax (Temp/ipykernel_11524/4158321875.py, line 2)

# Numpy

In [20]:
a = []

In [21]:
type(a)

list

In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np

In [24]:
# np.array()
# np.arange()
# np.linspace()
# np.random.randint()

# np.zeros()
# np.eye()
# np.ones()

In [25]:
l = [3,4,5,6,7,8]

In [26]:
type(l)

list

In [27]:
ar = np.array(l)

In [28]:
ar

array([3, 4, 5, 6, 7, 8])

In [29]:
ar = np.array([2,4,6,8,0,6,7,9])

In [30]:
ar

array([2, 4, 6, 8, 0, 6, 7, 9])

In [31]:
type(ar)

numpy.ndarray

In [32]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [33]:
np.arange(1,20,.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [34]:
np.linspace(1,20,30)

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [35]:
1-5===1,2,3,4,5
1-5 == 1.,1.5,2,.2,5-----

SyntaxError: invalid syntax (Temp/ipykernel_11524/4237191904.py, line 1)

In [36]:
np.random.randint(1,20,30)

array([18, 12,  2,  6, 17, 10, 11,  6, 13,  2,  6,  1,  5, 19,  8, 13, 15,
       11, 17, 19, 13, 15, 16,  8,  9, 19,  8,  4,  2, 11])

In [37]:
[0,0,0]
[0,0,0]
[0,0,0]

[0, 0, 0]

In [38]:
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
np.eye(3,3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
a = np.random.randint(1,9,54)

In [42]:
# a.reshape(3,4)

In [43]:
a = a.reshape(9,6)

In [44]:
a

array([[4, 3, 7, 1, 3, 1],
       [2, 3, 6, 6, 2, 4],
       [6, 1, 4, 8, 6, 4],
       [4, 7, 5, 4, 3, 5],
       [1, 8, 8, 4, 8, 8],
       [3, 7, 7, 4, 1, 8],
       [4, 5, 3, 7, 3, 2],
       [1, 2, 4, 5, 4, 8],
       [6, 5, 5, 5, 5, 2]])

In [45]:
a.size

54

In [46]:
a.ndim

2

In [47]:
a.shape

(9, 6)

In [48]:
a.dtype

dtype('int32')

In [49]:
a

array([[4, 3, 7, 1, 3, 1],
       [2, 3, 6, 6, 2, 4],
       [6, 1, 4, 8, 6, 4],
       [4, 7, 5, 4, 3, 5],
       [1, 8, 8, 4, 8, 8],
       [3, 7, 7, 4, 1, 8],
       [4, 5, 3, 7, 3, 2],
       [1, 2, 4, 5, 4, 8],
       [6, 5, 5, 5, 5, 2]])

In [50]:
a[3:]

array([[4, 7, 5, 4, 3, 5],
       [1, 8, 8, 4, 8, 8],
       [3, 7, 7, 4, 1, 8],
       [4, 5, 3, 7, 3, 2],
       [1, 2, 4, 5, 4, 8],
       [6, 5, 5, 5, 5, 2]])

In [51]:
a[0][2]

7

In [52]:
a[2][1]

1

In [53]:
a[3][1]

7

In [54]:
a.ravel()

array([4, 3, 7, 1, 3, 1, 2, 3, 6, 6, 2, 4, 6, 1, 4, 8, 6, 4, 4, 7, 5, 4,
       3, 5, 1, 8, 8, 4, 8, 8, 3, 7, 7, 4, 1, 8, 4, 5, 3, 7, 3, 2, 1, 2,
       4, 5, 4, 8, 6, 5, 5, 5, 5, 2])

In [55]:
a

array([[4, 3, 7, 1, 3, 1],
       [2, 3, 6, 6, 2, 4],
       [6, 1, 4, 8, 6, 4],
       [4, 7, 5, 4, 3, 5],
       [1, 8, 8, 4, 8, 8],
       [3, 7, 7, 4, 1, 8],
       [4, 5, 3, 7, 3, 2],
       [1, 2, 4, 5, 4, 8],
       [6, 5, 5, 5, 5, 2]])

In [56]:
x = np.random.randint(3,15,9).reshape(3,3)
y = np.random.randint(3,15,9).reshape(3,3)

In [57]:
x

array([[13,  3,  6],
       [11,  7,  8],
       [13, 11,  7]])

In [58]:
y

array([[ 5, 11,  8],
       [ 7, 12,  3],
       [ 3,  5, 10]])

In [59]:
x*y

array([[65, 33, 48],
       [77, 84, 24],
       [39, 55, 70]])

In [60]:
np.dot(x,y)

array([[104, 209, 173],
       [128, 245, 189],
       [163, 310, 207]])

In [61]:
x-y

array([[ 8, -8, -2],
       [ 4, -5,  5],
       [10,  6, -3]])

In [62]:
x+y

array([[18, 14, 14],
       [18, 19, 11],
       [16, 16, 17]])

In [63]:
x/y

array([[2.6       , 0.27272727, 0.75      ],
       [1.57142857, 0.58333333, 2.66666667],
       [4.33333333, 2.2       , 0.7       ]])

In [64]:
x//y

array([[2, 0, 0],
       [1, 0, 2],
       [4, 2, 0]], dtype=int32)

In [65]:
x%y

array([[3, 3, 6],
       [4, 7, 2],
       [1, 1, 7]], dtype=int32)

In [70]:
np.max(x)

13

In [71]:
x

array([[13,  3,  6],
       [11,  7,  8],
       [13, 11,  7]])

In [82]:
np.min(x,axis = 0)

array([11,  3,  6])

In [73]:
np.sqrt(x)

array([[3.60555128, 1.73205081, 2.44948974],
       [3.31662479, 2.64575131, 2.82842712],
       [3.60555128, 3.31662479, 2.64575131]])

In [80]:
np.mean(x)

8.777777777777779

In [75]:
np.mean(x,axis = 1)

array([ 7.33333333,  8.66666667, 10.33333333])

In [76]:
x

array([[13,  3,  6],
       [11,  7,  8],
       [13, 11,  7]])

In [77]:
np.mean(x,axis = 0)

array([12.33333333,  7.        ,  7.        ])

In [83]:
z = np.random.randint(3,20,27)

In [84]:
z

array([18,  7, 14, 14, 13, 15, 18, 18, 11,  9,  9, 10,  9, 16,  9, 13, 14,
       19,  7, 10, 10, 13, 11, 17,  9,  3, 19])

In [90]:
z = z.reshape(3,3,3)

In [87]:
z

array([[[18,  7, 14],
        [14, 13, 15],
        [18, 18, 11]],

       [[ 9,  9, 10],
        [ 9, 16,  9],
        [13, 14, 19]],

       [[ 7, 10, 10],
        [13, 11, 17],
        [ 9,  3, 19]]])

In [91]:
z[2][1][1]

11

In [95]:
z1 = np.random.randint(3,20,81)

In [96]:
z1

array([17, 17, 19, 18, 14, 17, 18, 11, 17, 15, 19, 17,  6,  3,  5, 19, 18,
       16, 17, 14, 16, 18,  3, 16, 12, 17, 18,  7, 16, 18,  4, 15, 15,  7,
       10, 19, 17, 14,  9, 17,  7, 15, 19,  6, 11,  5,  5,  8,  8, 16, 11,
       11, 19,  6, 13, 12, 17,  6, 10, 12, 16,  3, 19,  4, 10, 16,  4,  9,
        5,  9, 19, 12, 18, 17,  9,  5, 19,  8, 13, 19,  3])

In [100]:
z1 = z1.reshape(3,3,3,3)

In [101]:
z1

array([[[[17, 17, 19],
         [18, 14, 17],
         [18, 11, 17]],

        [[15, 19, 17],
         [ 6,  3,  5],
         [19, 18, 16]],

        [[17, 14, 16],
         [18,  3, 16],
         [12, 17, 18]]],


       [[[ 7, 16, 18],
         [ 4, 15, 15],
         [ 7, 10, 19]],

        [[17, 14,  9],
         [17,  7, 15],
         [19,  6, 11]],

        [[ 5,  5,  8],
         [ 8, 16, 11],
         [11, 19,  6]]],


       [[[13, 12, 17],
         [ 6, 10, 12],
         [16,  3, 19]],

        [[ 4, 10, 16],
         [ 4,  9,  5],
         [ 9, 19, 12]],

        [[18, 17,  9],
         [ 5, 19,  8],
         [13, 19,  3]]]])

In [106]:
z1[2][0][2][0]

16